version: '2.1'

services:

  infinity-shell:
    build:
      context: .
      dockerfile: ./shell/Dockerfile
    image: sawtooth-infinity-shell
    container_name: infinity-shell
    volumes:
      - .:/project/sawtooth-infinity
    command: |
      bash -c "
        infinity-protogen
        cd ../
        tail -f /dev/null
      "

  infinity-tp:
    build:
        context: .
        dockerfile: ./processor/Dockerfile
    image: sawtooth-infinity-tp
    container_name: infinity-tp
    volumes:
      - .:/project/sawtooth-infinity
    depends_on:
      - infinity-shell
    command: |
      bash -c "
        sleep 1
        tp-infinity -v -C tcp://validator:4004
      "

  infinity-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-infinity-rest-api
    container_name: infinity-rest-api
    volumes:
      - .:/project/sawtooth-infinity
    ports:
      - '8000:8000'
    depends_on:
      - infinity-shell
    command: |
      bash -c "
        infinity-rest-api \
          -B infinity-rest-api:8000 \
          -C validator:4004 \
          --db-host postgres \
          -vv
      "

  infinity-subscriber:
    build:
      context: .
      dockerfile: ./subscriber/Dockerfile
    image: sawtooth-infinity-subscriber
    container_name: infinity-subscriber
    volumes:
      - '.:/project/sawtooth-infinity'
    depends_on:
      - infinity-shell
      - postgres
    command: |
      bash -c "
        infinity-subscriber init \
          --db-host postgres \
          -vv
        sleep 3
        infinity-subscriber subscribe \
          --db-host postgres \
          -C tcp://validator:4004 \
          -vv
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  validator:
    image: hyperledger/sawtooth-validator:1.2
    container_name: sawtooth-validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          sawset proposal create -k /root/.sawtooth/keys/my_key.priv \
            sawtooth.consensus.algorithm.name=Devmode \
            sawtooth.consensus.algorithm.version=0.1 \
            -o config.batch
          sawadm genesis config-genesis.batch config.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050
      "

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.2
    expose:
      - 5050
    ports:
      - '5050:5050'
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust --connect tcp://validator:5050

  postgres:
    image: postgres:alpine
    container_name: infinity-postgres
    restart: always
    environment:
      POSTGRES_USER: sawtooth
      POSTGRES_PASSWORD: sawtooth
      POSTGRES_DB: infinity
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    container_name: infinity-adminer
    restart: always
    ports:
      - '8080:8080'